targets = [ "//:assign" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-array"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-ptr_container"
version = "branch=master"
